width = 10
height = 10
tiles = [
	["B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
	["B", "G", "G", "G", "G", "G", "G", "G", "G", "B"],
	["B", "G", "G", "G", "G", "G", "G", "G", "G", "B"],
	["B", "G", "G", "G", "G", "G", "G", "G", "G", "B"],
	["B", "G", "G", "G", "G", "G", "G", "G", "G", "B"],
	["B", "G", "G", "G", "G", "G", "G", "G", "G", "B"],
	["B", "G", "G", "G", "G", "G", "G", "G", "G", "B"],
	["B", "G", "G", "G", "G", "G", "G", "G", "G", "B"],
	["B", "G", "G", "G", "G", "G", "G", "G", "G", "B"],
	["B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
]
