[package]
name = "enfaria-common"
version = "0.1.0"
authors = ["Elinvynia <59487684+Elinvynia@users.noreply.github.com>"]
edition = "2018"

#[lib]
#crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
gdnative = "0.9"
toml = "0.5"
